apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
data:
  mcc: {{ .Values.lte.mcc | quote }}
  mnc: {{ .Values.lte.mnc | quote }}
  tac_0: {{ .Values.lte.tac_0 | quote }}
  mmeIpS1c: {{ .Values.lte.mmeIpS1c }}
