apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "oai-gnb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if  contains "ClusterIP" .Values.service.type }}
  clusterIP: None
{{- end }}
  ports:
    - name: sctpservers1ap
      protocol: SCTP
      port: 36413
      targetPort: 36413
    - name: s11
      # Port accessible outside cluster
      port: {{ .Values.service.gtpcPort }}
      # Port to forward to inside the pod
      targetPort: {{ .Values.service.gtpcPort }}
      protocol: UDP
  selector:
    {{- include "oai-gnb.selectorLabels" . | nindent 4 }}
