apiVersion: v1
kind: ServiceAccount
metadata:
  name: ue1-sa
  namespace: oai
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ue1-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ue1-sa
  namespace: oai
---
apiVersion: v1
data:
  band: "38"
  ru_local_if: net1
  ru_local_ip: 192.168.18.155
  ru_remote_ip: 192.168.18.153
kind: ConfigMap
metadata:
  name: ue1-config
  namespace: oai
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oai-ue1
  name: oai-ue1
  namespace: oai
spec:
  clusterIP: None
  ports:
  - name: if4p5-c
    port: 50000
    protocol: UDP
    targetPort: 50000
  - name: if4p5-u
    port: 50001
    protocol: UDP
    targetPort: 50001
  selector:
    app: oai-ue1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oai-ue1
  name: oai-ue1
  namespace: oai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-ue1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: ue1-net1
      labels:
        app: oai-ue1
    spec:
      containers:
      - args:
        - ./bin/entrypoint.sh; sleep infinity
        command:
        - /bin/sh
        - -c
        env:
        - name: RU_LOCAL_IF
          valueFrom:
            configMapKeyRef:
              key: ru_local_if
              name: ue1-config
        - name: RU_LOCAL_IP
          valueFrom:
            configMapKeyRef:
              key: ru_local_ip
              name: ue1-config
        - name: RU_REMOTE_IP
          valueFrom:
            configMapKeyRef:
              key: ru_remote_ip
              name: ue1-config
        - name: BAND
          valueFrom:
            configMapKeyRef:
              key: band
              name: ue1-config
        image: image-registry.openshift-image-registry.svc:5000/oai/oai-ue:develop-vco3
        imagePullPolicy: Always
        name: ue1
        ports:
        - containerPort: 50000
          name: if4p5-c
        - containerPort: 50001
          name: if4p5-u
        securityContext:
          privileged: true
      - command:
        - /bin/sleep
        - infinity
        image: corfr/tcpdump
        name: tcpdump
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      serviceAccountName: ue1-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ue1-net1
  namespace: oai
spec:
  config: '{ "cniVersion": "0.3.0", "type": "macvlan", "master": "bond0", "mode":
    "bridge", "ipam": { "type": "static", "addresses": [ { "address": "192.168.18.155/24",
    "gateway": "192.168.18.1" } ] } }'
