apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oai-spgwc.fullname" . }}
  labels:
    {{- include "oai-spgwc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "oai-spgwc.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "oai-spgwc.selectorLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: spgwc-net1, spgwc-net2
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "oai-spgwc.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: "SGW_S11_INTERFACE"
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: sgwS11If
          - name: "PGW_SX_INTERFACE"
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: pgwSxIf
          - name: UE_IP_ADDRESS_POOL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: ueIpAddressPool
          - name: UE_DNS_SERVER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-configmap
                key: ueDnsServer
        command:
          - /bin/sleep
          - infinity
        image: corfr/tcpdump
        command:
          - /bin/sleep
          - infinity
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: spgwc-sa
      terminationGracePeriodSeconds: 30

