apiVersion: apps/v1
kind: Deployment
metadata:
  name: oai-spgwu
  labels:
    app: oai-spgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oai-spgwu
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oai-spgwu
      annotations:
        k8s.v1.cni.cncf.io/networks: spgwu-net1, spgwu-net2
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: spgwu
        image: image-registry.openshift-image-registry.svc:5000/oai/oai-spgwu
        #command: ['sh', '-c', 'sleep 6000']
        securityContext:
          privileged: true
        ports:
        - containerPort: 8805
          name: oai-spgwu
        - containerPort: 2152
          name: s11
        env:
          # MME env vars
          - name: 
            valueFrom:
              configMapKeyRef:
                name: spgwu-config
                key: sgw_s1u_if
          - name: 
            valueFrom:
              configMapKeyRef:
                name: spgwu-config
                key: sgw_sx_if
          - name: 
            valueFrom:
              configMapKeyRef:
                name: spgwu-config
                key: pgw_sgi_if
          - name: 
            valueFrom:
              configMapKeyRef:
                name: spgwu-config
                key: net_ue_ip
          - name: 
            valueFrom:
              configMapKeyRef:
                name: spgwu-config
                key: pgwc_sx_ip
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: spgwu-sa
      terminationGracePeriodSeconds: 30
